export const ADD_TODO = "ADD_TODO";
export const REMOVE_TODO = "REMOVE_TODO";
export const REMOVE_ALL_TODOS = "REMOVE_ALL_TODOS";
export const UPDATE_TODO = "UPDATE_TODO";
export const TOGGLE_TODO = "TOGGLE_TODO";
export const START_EDIT_TODO = "START_EDIT_TODO";
export const CLEAR_NOTIFICATION_TODO = "CLEAR_NOTIFICATION_TODO";
export const UPDATE_MESSAGE_TODO = "UPDATE_MESSAGE_TODO";
